import logging
from typing import Optional
from fastapi import APIRouter, Depends, Query, status
from fastapi.responses import StreamingResponse
from app.dependencies.auth import get_current_secretary
from app.models.chat import ChatRequest, HistoryResponse
from app.services import chat_service, history_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/chat", tags=["Chat"])


@router.post(
    "/message",
    summary="Send a message and stream AI response",
    description="Streams the AI assistant's response live via Server-Sent Events (SSE). Requires valid secretary JWT.",
    response_class=StreamingResponse,
    status_code=status.HTTP_200_OK,
)
async def send_chat_message(
    request: ChatRequest,
    current_user: dict = Depends(get_current_secretary),
):
    """
    Primary chat endpoint.
    - Requires Authorization: Bearer <jwt> header issued by the Node.js backend.
    - Automatically overrides and binds secretary_id and thread_id to the verified token's userId.
    - Saves the secretary's message to MongoDB permanent history.
    - Streams tokens generated by LangGraph in real time via SSE (text/event-stream).
    - Automatically persists the complete AI reply to MongoDB upon stream completion.
    """
    # Security: enforce caller's verified userId from the JWT payload
    verified_secretary_id = current_user["user_id"]
    request.secretary_id = verified_secretary_id
    request.thread_id = f"secretary_{verified_secretary_id}"

    logger.info("Authenticated secretary ID: %d sending message.", verified_secretary_id)

    return StreamingResponse(
        chat_service.stream_chat(request),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disables proxy buffering (useful for Nginx in production)
        },
    )


@router.get(
    "/history",
    summary="Get permanent conversation history",
    description="Returns the full, chronological chat history for the authenticated secretary.",
    response_model=HistoryResponse,
    status_code=status.HTTP_200_OK,
)
async def get_chat_history(
    limit: int = Query(default=50, ge=1, le=200, description="Max messages to return"),
    skip: int = Query(default=0, ge=0, description="Messages to skip for pagination"),
    current_user: dict = Depends(get_current_secretary),
):
    """
    Retrieve permanent conversation history for UI display.
    Securely derives the thread_id from the authenticated caller's JWT token.
    """
    # Security: bound to the authenticated caller's verified ID
    thread_id = f"secretary_{current_user['user_id']}"

    messages = await history_service.get_history(thread_id=thread_id, limit=limit, skip=skip)
    total_count = await history_service.get_message_count(thread_id=thread_id)

    return HistoryResponse(
        thread_id=thread_id,
        messages=messages,
        total_count=total_count,
    )
