import logging
from fastapi import APIRouter, Query, status
from fastapi.responses import StreamingResponse
from app.models.chat import ChatRequest, HistoryResponse
from app.services import chat_service, history_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/chat", tags=["Chat"])


@router.post(
    "/message",
    summary="Send a message and stream AI response",
    description="Streams the AI assistant's response live via Server-Sent Events (SSE).",
    response_class=StreamingResponse,
    status_code=status.HTTP_200_OK,
)
async def send_chat_message(request: ChatRequest):
    """
    Primary chat endpoint.
    - Saves the secretary's message to MongoDB permanent history.
    - Streams tokens generated by LangGraph / Gemini in real time via SSE (text/event-stream).
    - Automatically persists the complete AI reply to MongoDB upon stream completion.
    """
    return StreamingResponse(
        chat_service.stream_chat(request),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disables proxy buffering (useful for Nginx in production)
        },
    )


@router.get(
    "/history",
    summary="Get permanent conversation history",
    description="Returns the full, chronological chat history for a thread from MongoDB.",
    response_model=HistoryResponse,
    status_code=status.HTTP_200_OK,
)
async def get_chat_history(
    thread_id: str = Query(..., description="Thread identifier (e.g. secretary_12)"),
    limit: int = Query(default=50, ge=1, le=200, description="Max messages to return"),
    skip: int = Query(default=0, ge=0, description="Messages to skip for pagination"),
):
    """
    Retrieve permanent conversation history for UI display.
    """
    messages = await history_service.get_history(thread_id=thread_id, limit=limit, skip=skip)
    total_count = await history_service.get_message_count(thread_id=thread_id)

    return HistoryResponse(
        thread_id=thread_id,
        messages=messages,
        total_count=total_count,
    )
